/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as EscapeRouteImport } from './routes/escape'
import { Route as HowCookedRouteImport } from './routes/how-cooked'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as CompareSlugsRouteImport } from './routes/compare/$slugs'
import { Route as CountryIndexRouteImport } from './routes/country/index'
import { Route as CountrySlugRouteImport } from './routes/country/$slug'
import { Route as ForIndexRouteImport } from './routes/for/index'
import { Route as ForVerticalRouteImport } from './routes/for/$vertical'
import { Route as ProcessorSlugRouteImport } from './routes/processor/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const EscapeRoute = EscapeRouteImport.update({
  id: '/escape',
  path: '/escape',
  getParentRoute: () => rootRouteImport,
} as any)
const HowCookedRoute = HowCookedRouteImport.update({
  id: '/how-cooked',
  path: '/how-cooked',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugsRoute = CompareSlugsRouteImport.update({
  id: '/compare/$slugs',
  path: '/compare/$slugs',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/country/',
  path: '/country/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountrySlugRoute = CountrySlugRouteImport.update({
  id: '/country/$slug',
  path: '/country/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIndexRoute = ForIndexRouteImport.update({
  id: '/for/',
  path: '/for/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVerticalRoute = ForVerticalRouteImport.update({
  id: '/for/$vertical',
  path: '/for/$vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessorSlugRoute = ProcessorSlugRouteImport.update({
  id: '/processor/$slug',
  path: '/processor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/escape': typeof EscapeRoute
  '/how-cooked': typeof HowCookedRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/compare/$slugs': typeof CompareSlugsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/for/$vertical': typeof ForVerticalRoute
  '/processor/$slug': typeof ProcessorSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/country/': typeof CountryIndexRoute
  '/for/': typeof ForIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/escape': typeof EscapeRoute
  '/how-cooked': typeof HowCookedRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/compare/$slugs': typeof CompareSlugsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/for/$vertical': typeof ForVerticalRoute
  '/processor/$slug': typeof ProcessorSlugRoute
  '/compare': typeof CompareIndexRoute
  '/country': typeof CountryIndexRoute
  '/for': typeof ForIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/corrections': typeof CorrectionsRoute
  '/escape': typeof EscapeRoute
  '/how-cooked': typeof HowCookedRoute
  '/methodology': typeof MethodologyRoute
  '/privacy': typeof PrivacyRoute
  '/rankings': typeof RankingsRoute
  '/sources': typeof SourcesRoute
  '/terms': typeof TermsRoute
  '/compare/$slugs': typeof CompareSlugsRoute
  '/country/$slug': typeof CountrySlugRoute
  '/for/$vertical': typeof ForVerticalRoute
  '/processor/$slug': typeof ProcessorSlugRoute
  '/compare/': typeof CompareIndexRoute
  '/country/': typeof CountryIndexRoute
  '/for/': typeof ForIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/corrections'
    | '/escape'
    | '/how-cooked'
    | '/methodology'
    | '/privacy'
    | '/rankings'
    | '/sources'
    | '/terms'
    | '/compare/$slugs'
    | '/country/$slug'
    | '/for/$vertical'
    | '/processor/$slug'
    | '/compare/'
    | '/country/'
    | '/for/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/corrections'
    | '/escape'
    | '/how-cooked'
    | '/methodology'
    | '/privacy'
    | '/rankings'
    | '/sources'
    | '/terms'
    | '/compare/$slugs'
    | '/country/$slug'
    | '/for/$vertical'
    | '/processor/$slug'
    | '/compare'
    | '/country'
    | '/for'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/corrections'
    | '/escape'
    | '/how-cooked'
    | '/methodology'
    | '/privacy'
    | '/rankings'
    | '/sources'
    | '/terms'
    | '/compare/$slugs'
    | '/country/$slug'
    | '/for/$vertical'
    | '/processor/$slug'
    | '/compare/'
    | '/country/'
    | '/for/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CorrectionsRoute: typeof CorrectionsRoute
  EscapeRoute: typeof EscapeRoute
  HowCookedRoute: typeof HowCookedRoute
  MethodologyRoute: typeof MethodologyRoute
  PrivacyRoute: typeof PrivacyRoute
  RankingsRoute: typeof RankingsRoute
  SourcesRoute: typeof SourcesRoute
  TermsRoute: typeof TermsRoute
  CompareSlugsRoute: typeof CompareSlugsRoute
  CountrySlugRoute: typeof CountrySlugRoute
  ForVerticalRoute: typeof ForVerticalRoute
  ProcessorSlugRoute: typeof ProcessorSlugRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CountryIndexRoute: typeof CountryIndexRoute
  ForIndexRoute: typeof ForIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escape': {
      id: '/escape'
      path: '/escape'
      fullPath: '/escape'
      preLoaderRoute: typeof EscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-cooked': {
      id: '/how-cooked'
      path: '/how-cooked'
      fullPath: '/how-cooked'
      preLoaderRoute: typeof HowCookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slugs': {
      id: '/compare/$slugs'
      path: '/compare/$slugs'
      fullPath: '/compare/$slugs'
      preLoaderRoute: typeof CompareSlugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/': {
      id: '/country/'
      path: '/country'
      fullPath: '/country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$slug': {
      id: '/country/$slug'
      path: '/country/$slug'
      fullPath: '/country/$slug'
      preLoaderRoute: typeof CountrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/': {
      id: '/for/'
      path: '/for'
      fullPath: '/for/'
      preLoaderRoute: typeof ForIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$vertical': {
      id: '/for/$vertical'
      path: '/for/$vertical'
      fullPath: '/for/$vertical'
      preLoaderRoute: typeof ForVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processor/$slug': {
      id: '/processor/$slug'
      path: '/processor/$slug'
      fullPath: '/processor/$slug'
      preLoaderRoute: typeof ProcessorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CorrectionsRoute: CorrectionsRoute,
  EscapeRoute: EscapeRoute,
  HowCookedRoute: HowCookedRoute,
  MethodologyRoute: MethodologyRoute,
  PrivacyRoute: PrivacyRoute,
  RankingsRoute: RankingsRoute,
  SourcesRoute: SourcesRoute,
  TermsRoute: TermsRoute,
  CompareSlugsRoute: CompareSlugsRoute,
  CountrySlugRoute: CountrySlugRoute,
  ForVerticalRoute: ForVerticalRoute,
  ProcessorSlugRoute: ProcessorSlugRoute,
  CompareIndexRoute: CompareIndexRoute,
  CountryIndexRoute: CountryIndexRoute,
  ForIndexRoute: ForIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
